# Exercises

In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.


### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

npheight = np.array(height)
npweight = np.array(weight)

bmi = npweight / (npheight ** 2) * 730

print(bmi)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [3]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

def makeMatrix(low,high,shape = (np.random.randint(3,6),np.random.randint(3,6)), data_type = int):
    if data_type == int:
        return np.random.randint(low, high, shape)
    else:
        return np.random.uniform(low, high, shape)
    
print(makeMatrix(0,10))
print(makeMatrix(0,10,(3,3), data_type = float))

[[9 5 5 3 3]
 [0 0 8 7 8]
 [8 1 7 9 0]
 [2 2 9 1 1]
 [2 1 1 6 1]]
[[4.74647578 3.51133398 4.56281191]
 [4.70205695 9.48495492 2.7684947 ]
 [4.93427201 8.75596806 3.82336126]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [9]:
# Ryan said: comparing average values of the two years is fine.

import csv
import numpy as np
import statistics

#Test to make sure you have the correct data



In [19]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

rs2017 = load_data('redsox_2017_hitting.txt')
rs2018 = load_data('redsox_2018_hitting.txt')

all_slg1 = rs2017['SLG']
all_slg2 = rs2018['SLG']

slger1 = np.array(all_slg1)
slger2 = np.array(all_slg2)

final1 = statistics.mean(slger1)
final2 = statistics.mean(slger2)

print(f"Yo Ryan check it out, 2017 data my friend {final1}")
print(f"Yo Ryan check it out, 2018 data my friend {final2}")

Yo Ryan check it out, 2017 data my friend 0.393347829580307
Yo Ryan check it out, 2018 data my friend 0.38750001788139343
